spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: test-service
              uri: lb://TEST-SERVICE
              predicates:
                   - Path=/api/test/route/**
              filters:
                   - RewritePath=/api/test/route, /test/route


            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                    - Path=/api/auth/**
              filters:
                    - RewritePath=/api/auth/(?<segment>.*), /auth/${segment}
