spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: admin-service
              uri: lb://ADMIN-SERVICE
              predicates:
                   - Path=/api/admin/**
              filters:
                   - RewritePath=/api/admin/(?<segment>.*), /admin/${segment}


            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                    - Path=/api/auth/**
              filters:
                    - RewritePath=/api/auth/(?<segment>.*), /auth/${segment}

            - id: STATION-SERVICE
              uri: lb://STATION-SERVICE
              predicates:
                - Path=/api/stations/**
              filters:
                - RewritePath=/api/stations/(?<segment>.*), /stations/${segment}
